= Key Management App for LiveCD

This Docker application supports smartcard key management tools from GPG and OpenSC. It is
intended to be started from the PVZDLiveCD.


== Supported Smart Cards
There is out-of-the box support for cards, such as:

- OpenPGP card
- JavaCard with installed Muscle applet
- other PKI smartcards supported by OpenSC

To install a proprieatary smart card driver create an image based on this one and include the
driver installation in the Dockerfile. An example for Safenet eToken Pro is in the keymgmt-safenetac
project.

Commands use PKCS11_CARD_DRIVER to point to the card driver.
The default value is '/usr/lib64/pkcs11/opensc-pkcs11.so'.

== RSA key generation for PKCS#11

Some smartcard-based HSMs do not support the transfer of on-card generated keys to other devices.
For those devices the approach is to generate keys off-card and upload the later. Doing this
on an air-gapped LiveCD-based system is recommended then.

=== Key-to-card approach

Example how to genrate keys and copy to card:

    ./dscripts/run.sh -i  # start container if not yet running
    /scripts/x509_create_keys_on_disk.sh -n metadata -s /C=AT/ST=Wien/L=Wien/O=Testfirma/OU=IT/CN=localhost
    /scripts/pkcs11_key_to_token.sh -c metadata_crt.der -i -k metadata_key.der -l mdsign -n test -s Secret.2 -t Secret.1 -v

=== Key-on-card approach

    /scripts/pkcs11_key_to_token.sh -c metadata_crt.der -i -k metadata_key.der -l mdsign -n test -s Secret.2 -t Secret.1 -v

== GPG Support

See the link:docs/GPG-howto.adoc[GPG-howto].

== Key Archiving Tools

=== N out of N Key Splitting

A cryptographically secure key splitting scheme for n out of n parties, e.g. with 3 parties:

     secret-split -n 3 localhost_key_pkcs1.pem
        or
     secret-split --random-source /dev/urandom -n 3 localhost_key_pkcs1.pem  # do not wait for entropy on /dev/random

To recover the original key:

    secret-combine -o localhost_key_pkcs1.pem localhost_key_pkcs1.pem.part?

=== Print Key as QR-Code

    # generate eps
    cat localhost_key_pkcs1.pem | qrencode –o localhost_key_pkcs1.eps
    # spool to default printer: move file to docker host, spool from there


Print QR-code (e.g. using Libre Office), a SHA256 checksum and the related public key.


== Known Limitations

Plugging and unplugging readers and cards is not signalled to the application container. (This
would need and improved dbus integration with the container.)

Starting haveged before using gpg may lead to an "signing failed: Operation cancelled" error.
Workaround: Check available entropy before crypto ops:

    cat /proc/sys/kernel/random/entropy_avail